### ISSUE TITLE
Explain what cooking means

### ISSUE THREAD

**Issue by flavius** [vityafx/cargo-cook#2]
Please explain in one sentence in the README what cooking means. I had to research for this. Helps with marketing it better.

**Comment by vityafx** [comment]
Well, I am not native english speaker. When I named the project  I chose this word thinking about "cooking a cake.". I did not think about naming much actually. So anyone can still propose the name to use.

**Comment by flavius** [comment]
I was not even proposing a name change, `cook` is fine. Just explain in a sentence in the README.md file what cooking means.

**Comment by vityafx** [comment]
@flavius oh, yes, I will do this, sorry for misunderstanding.

**Comment by vityafx** [comment]
@flavius Is it now okay?

**Comment by flavius** [comment]
@vityafx perfect!
