### ISSUE TITLE
Include strip in cooking?

### ISSUE THREAD

**Issue by colindean** [vityafx/cargo-cook#4]
`strip`ping binaries seems like a very common task for release builds. While certainly possible with a pre-hook script, it'd be nice if cargo-cook could do that OOTB.

**Comment by vityafx** [comment]
This is a good idea of course and I had done that earlier actually if I have had a strong opinion about what should do it - either a `cargo-cook` or `pre-hook` scripts. Now `cargo-cook` does exactly nothing more than packaging and everything else is left to customizable scripts as you already mentioned `pre-hook` script.

**Comment by vityafx** [comment]
@colindean Is it okay for you to call `strip` in the `pre-cook` script?

**Comment by colindean** [comment]
I've not tried it yet. I'm due to revisit the relevant project in November.

**Comment by vityafx** [comment]
@colindean Hey! So how was your November last year? :)

**Comment by colindean** [comment]
I left the company at the end of it! I've not really had a project with a need to use cargo-cook with since.

**Comment by vityafx** [comment]
@colindean Okay, thanks for the response :) If anyone sees this comment and still wants to include strip inside the cargo-cook and not pre-cook script and can provide me with a good rationale, create another issue please.
